"use client";
import { useEffect, useRef, useState } from "react";
import { Bot, MessageCircle, Send, X } from "lucide-react";

export function ChatBot({ context }: { context: any }) {
  const [open,setOpen]=useState(false); const [input,setInput]=useState(""); const [loading,setLoading]=useState(false);
  const [messages,setMessages]=useState<{role:"user"|"assistant";content:string}[]>([{role:"assistant",content:"SatQueryX Copilot ready. Ask about the active mission, remote-sensing concepts, or the evidence produced by the current workflow."}]);
  const endRef=useRef<HTMLDivElement>(null); useEffect(()=>endRef.current?.scrollIntoView({behavior:"smooth"}),[messages,open]);
  async function send(text?:string){const q=(text??input).trim();if(!q||loading)return;setInput("");setMessages(m=>[...m,{role:"user",content:q}]);setLoading(true);try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:context.provider??"openrouter",query:q,workflow:"Copilot contextual explanation",primary:null,secondary:null,observations:context})});const d=await r.json();setMessages(m=>[...m,{role:"assistant",content:d.configured&&d.answer?d.answer:(d.message||"AI language layer is not configured. SatQueryX will not fabricate a response.")}]);}catch(e){setMessages(m=>[...m,{role:"assistant",content:e instanceof Error?e.message:"Copilot request failed."}]);}finally{setLoading(false)}}
  return <><div className="chat-toggle"><button type="button" onClick={()=>setOpen(!open)} className="btn btn--secondary"><MessageCircle size={14}/>{open?"Close Copilot":"SatQuery Copilot"}</button></div>{open&&<div className="chat-drawer"><div className="flex items-center justify-between border-b border-white/8 bg-white/[.025] p-3"><div className="flex items-center gap-2"><Bot size={16} className="text-cyan-300"/><div><div className="text-sm font-semibold">SatQuery Copilot</div><div className="text-[10px] text-slate-500">Context-aware mission assistant</div></div></div><button className="btn btn--ghost btn--sm" onClick={()=>setOpen(false)}><X size={14}/></button></div><div className="flex gap-2 overflow-x-auto border-b border-white/8 p-2"><button className="btn btn--ghost btn--sm" onClick={()=>send("Explain the current workflow")}>Explain workflow</button><button className="btn btn--ghost btn--sm" onClick={()=>send("Explain the evidence")}>Explain evidence</button><button className="btn btn--ghost btn--sm" onClick={()=>send("What should I verify before trusting this result?")}>Trust checklist</button></div><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`chat-bubble ${m.role}`}>{m.content}</div>)}{loading&&<div className="chat-bubble assistant">SatQueryX is reasoning…</div>}<div ref={endRef}/></div><div className="chat-footer"><input className="input flex-1" placeholder="Ask SatQueryX…" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}}/><button className="btn btn--primary btn--sm" onClick={()=>send()} disabled={!input.trim()||loading}><Send size={13}/></button></div></div>}</>;
}
