"use client";
import { useState } from "react";
import { Globe2, X } from "lucide-react";

const sectors = [
  ["Delhi NCR",28.6139,77.2090],["Kolkata",22.5726,88.3639],["Mumbai",19.0760,72.8777],["Bengaluru",12.9716,77.5946],["Dubai",25.2048,55.2708],["Gangotri",30.93,79.08]
] as const;

export function GodsEyeLauncher({ open,onClose,onSelect }:{open:boolean;onClose:()=>void;onSelect:(lat:number,lon:number,name:string)=>void}){
  const [selected,setSelected]=useState(0); if(!open)return null;
  return <div className="fixed inset-0 z-[120] flex flex-col bg-[#07090E]">
    <div className="flex items-center justify-between border-b border-cyan-300/20 bg-black/60 px-4 py-3"><div className="flex items-center gap-2"><Globe2 className="text-cyan-300" size={17}/><div><div className="text-sm font-semibold tracking-wide">GOD&apos;S EYE · EARTH EXPLORER</div><div className="text-[9px] uppercase tracking-[.18em] text-slate-600">Spatial navigation workspace</div></div></div><button className="btn btn--ghost btn--sm" onClick={onClose}><X size={15}/></button></div>
    <div className="grid min-h-0 flex-1 lg:grid-cols-[1fr_300px]"><div className="grid-bg relative flex min-h-[55vh] items-center justify-center overflow-hidden"><div className="absolute inset-0 opacity-60" style={{backgroundImage:"radial-gradient(circle at 50% 48%, rgba(61,214,208,.18) 0 11%, rgba(15,32,46,.22) 24%, transparent 42%), repeating-radial-gradient(circle at 50% 48%, rgba(61,214,208,.08) 0 1px, transparent 2px 60px)"}}/><div className="relative h-[min(56vw,520px)] w-[min(56vw,520px)] max-h-[58vh] max-w-[58vh] rounded-full border border-cyan-300/20 bg-[radial-gradient(circle_at_35%_30%,#315f77,#102637_54%,#030912_72%)] shadow-[0_0_90px_rgba(61,214,208,.18),inset_-30px_-30px_55px_rgba(0,0,0,.65)]"><div className="absolute inset-[12%] rounded-full border border-cyan-200/10"/><div className="absolute inset-[25%] rounded-full border border-cyan-200/10"/><div className="absolute left-1/2 top-[18%] bottom-[18%] w-px -translate-x-1/2 bg-cyan-200/10"/><div className="absolute top-1/2 left-[12%] right-[12%] h-px -translate-y-1/2 bg-cyan-200/10"/></div><div className="absolute bottom-5 left-5 rounded-xl border border-white/10 bg-black/55 p-3 text-[10px] text-slate-500 backdrop-blur"><div className="uppercase tracking-[.16em] text-cyan-200">Selected sector</div><div className="mt-1 text-xs text-slate-200">{sectors[selected][0]}</div><div className="mt-1 font-mono">{Number(sectors[selected][1]).toFixed(4)}°, {Number(sectors[selected][2]).toFixed(4)}°</div></div></div><aside className="border-l border-white/8 bg-black/20 p-4"><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-slate-500">Quick sectors</div><div className="mt-3 space-y-2">{sectors.map(([name,lat,lon],i)=><button key={name} onClick={()=>setSelected(i)} className={`w-full rounded-lg border p-3 text-left ${i===selected?"border-cyan-300/30 bg-cyan-300/10":"border-white/8 bg-white/[.02]"}`}><div className="text-xs text-slate-200">{name}</div><div className="mt-1 font-mono text-[9px] text-slate-600">{lat.toFixed(3)}, {lon.toFixed(3)}</div></button>)}</div><button className="btn btn--primary btn--full mt-4" onClick={()=>onSelect(Number(sectors[selected][1]),Number(sectors[selected][2]),sectors[selected][0])}>Load selected sector</button><div className="mt-3 text-[9px] leading-4 text-slate-600">The explorer selects an AOI; scientific analysis remains in the SatQueryX pipeline.</div></aside></div>
  </div>;
}
