"use client";
import dynamic from "next/dynamic";
import { Crosshair, Image as ImageIcon, Map, ScanLine, Sparkles } from "lucide-react";
import { useState } from "react";
import type { FileState } from "./types";
const AOIMap = dynamic(() => import("@/components/aoi-map"), { ssr: false });
export function MissionViewer({ primary, secondary, center, onCenter, snippet, onSnippet, result, onOpenEarth }: { primary:FileState; secondary:FileState; center:[number,number]; onCenter:(c:[number,number])=>void; snippet:any; onSnippet:(s:any)=>void; result:any; onOpenEarth:()=>void }) {
  const [mode,setMode]=useState<"aoi"|"imagery">("aoi");
  const payload=result?.result??result??{}; const grounding=payload?.grounding||payload?.changed_regions||[];
  return <div className="panel flex min-h-[560px] min-w-0 flex-col overflow-hidden">
    <div className="flex items-center justify-between border-b border-white/8 bg-white/[.02] px-3 py-2"><div className="flex items-center gap-2"><Map size={15} className="text-cyan-300"/><div><div className="text-sm font-semibold">Mission Viewer</div><div className="text-[10px] text-slate-500">AOI, imagery and spatial evidence</div></div></div><div className="flex items-center gap-1"><button className={`btn btn--sm ${mode==='aoi'?"btn--primary":"btn--ghost"}`} onClick={()=>setMode("aoi")}><Map size={12}/>AOI Map</button><button className={`btn btn--sm ${mode==='imagery'?"btn--primary":"btn--ghost"}`} onClick={()=>setMode("imagery")}><ImageIcon size={12}/>Scene Viewer</button><button className="btn btn--secondary btn--sm" onClick={onOpenEarth}><Sparkles size={12}/>3D Earth</button></div></div>
    <div className="relative min-h-0 flex-1">{mode==='aoi'?<AOIMap center={center} onCenterChange={onCenter} snippet={snippet} onSnippetChange={onSnippet}/>:<div className={`grid h-full min-h-[500px] gap-px bg-white/8 ${secondary.file?"grid-cols-1 md:grid-cols-2":"grid-cols-1"}`}>{[primary,secondary].map((state,i)=>i===1&&!secondary.file?null:<div key={i} className="relative flex items-center justify-center overflow-hidden bg-[#060c11]"><div className="absolute left-3 top-3 z-10 rounded border border-white/10 bg-black/60 px-2 py-1 text-[9px] uppercase tracking-[.14em] text-slate-400">{i===0?"Primary / T0":"Secondary / T1 or SAR"}</div>{state.preview?<div className="relative h-full w-full"><img src={state.preview} alt="satellite scene" className="absolute inset-0 h-full w-full object-contain"/>{i===0&&grounding.length>0&&<svg className="pointer-events-none absolute inset-0 h-full w-full">{grounding.slice(0,12).map((g:any,k:number)=>{const b=g.bbox;if(!Array.isArray(b)||b.length!==4)return null;const[x,y,w,h]=b;return <g key={k}><rect x={`${x}%`} y={`${y}%`} width={`${w}%`} height={`${h}%`} fill="rgba(61,214,208,.12)" stroke="rgba(61,214,208,.9)" strokeWidth="2"/><text x={`${x}%`} y={`${Math.max(2,y-1)}%`} fill="#7ff7f2" fontSize="11">{g.label||`Region ${k+1}`}</text></g>})}</svg>}</div>:<div className="text-center text-xs text-slate-600"><ScanLine size={28} className="mx-auto mb-2 opacity-40"/>No scene preview available</div>}</div>)}</div>}
      <div className="absolute bottom-3 left-3 right-3 z-20 flex flex-wrap items-center gap-2"><div className="glass rounded-lg px-2 py-1 text-[9px] text-slate-400">CENTER <span className="font-mono text-cyan-200">{center[0].toFixed(4)}, {center[1].toFixed(4)}</span></div>{snippet&&<div className="glass rounded-lg px-2 py-1 text-[9px] text-slate-400">SNIPPET <span className="text-cyan-200">{snippet.type}</span></div>} {mode==='aoi'&&<div className="ml-auto glass flex items-center gap-1 rounded-lg px-2 py-1 text-[9px] text-slate-500"><Crosshair size={11} className="text-cyan-300"/>Draw a rectangle or polygon on the map</div>}</div>
    </div>
  </div>;
}
